import pandas as pd
from glob import glob
import orjson
import os
import datetime


def parse_instafiles(username, path, initial_path):
    """ 
    This function loads in all the json files generated by the      instaloader package and parses it into a csv file.
    """
    #print('Entering provided directory...')
    os.chdir(os.path.join(path+"/data/", username))
    
    columns = ['filename', 'datetime', 'type', 'locations_id', 'locations_name', 'mentions', 'hashtags', 'video_duration']
    
    dataframe = pd.DataFrame(columns=[])
    
    #print('Traversing file tree...')
    
    glob('*UTC.json')
    
    for file in glob('*UTC.json'):
        with open(file, 'r') as filecontent:
            filename = filecontent.name
            #print('Found JSON file: ' + filename + '. Loading...')
            
            try:
                metadata = orjson.loads(filecontent.read())
            
            except IOError as e:
                #print("I/O Error. Couldn't load file. Trying the next one...")
                continue
            else:
                pass
            #print('Collecting relevant metadata...')
            time = datetime.date.fromtimestamp(int(metadata['node']['taken_at_timestamp']))
            type_ = metadata['node']['__typename']
            likes = metadata['node']['edge_media_preview_like']['count']     
            comments = metadata['node']['edge_media_to_comment']['count']
            total_interaction = metadata['node']['edge_media_preview_like']['count'] + metadata['node']['edge_media_to_comment']['count']
            username = metadata['node']['owner']['username']
            fullname = metadata['node']['owner']['full_name']
            followers = metadata['node']['owner']['edge_followed_by']['count']
            url = metadata['node']["display_url"]
            try:
                text = metadata['node']['edge_media_to_caption']['edges'][0]['node']['text']
            except:
                text = ""
            try:
                video_view_count = metadata['node']['video_view_count']
            except:
                video_view_count = ""
            try:
                post_id = metadata['node']['id']
            except:
                post_id = ""
            minedata = {'post_id' : post_id, 'username' : username, 'fullname':fullname, 'followers' : followers, 'post_type': type_, 'time': time, 
                    'text': text, 'likes': likes, 'comments' : comments, "total_interaction":total_interaction,     'video_view_count':video_view_count,  'url':url}
            #print('Writing to dataframe...')
            dataframe = dataframe.append(minedata, ignore_index=True)
            #print('Closing file...')
            del metadata
            filecontent.close()
    #print('Storing dataframe to CSV file...')
    #print('Done.')
    dataframe['source'] = 'Instagram'
    os.chdir(initial_path)
    return dataframe